

services:

  server:
    build:
      context: ./falcon_server/
      #context: ./express_server/
    expose:
      - 8000
    ports:
      - 8000:8000
    init: true

  client:
    build:
      #context: ./vue_client/
      context: ./react_client/
    expose:
      - 8001
    ports:
      - 8001:8001
    links:
        - server
    init: true

